### ISSUE TITLE
sample intermittently has no data

### ISSUE THREAD

**Issue by tmazor** [hms-dbmi/OncoThreads#223]
P24_pri loads without data semi-consistently. Screenshot below is from "Low-Grade Gliomas with CNA and mRNA-seq". I've also see this with "Low-Grade Gliomas with all data types", so it's not study specific. If I re-load the study, the data is there.

I've seen this happen multiple times, on different days, and always with that one sample.

![image](https://user-images.githubusercontent.com/10508276/68515968-b37a5700-0250-11ea-8858-3ffc6abdc931.png)

**Comment by ThHarbig** [comment]
This is because of an error in the data itself in all low grade glioma studies. A sample has been assigned to the wrong patient in the timeline SPECIMEN file. As this wrong assignment is not consistent in the other files/api calls, data cannot be associated with that sample of the patient. This error only occurs sometimes because if there are multiple samples per patient in a timepoint we chose one randomly.

**Comment by tmazor** [comment]
Ohhh yes I see this in the data now... there's a sample from P26 which is assigned to P24 by mistake in that one file. It is like this in the original data files which I used as the basis for every version of the study. Thanks for figuring that out!
